name: Build - macOS Only
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      ci_version:
        required: true
        type: string
  # This adds the manual trigger button in the GitHub Actions tab
  workflow_dispatch:
    inputs:
      ci_version:
        description: 'Version string for the build'
        required: true
        default: 'manual-build'

jobs:
  build:
    # Explicitly set to macOS and remove the matrix
    runs-on: macos-15
    env:
      # This handles input from either a workflow_call or a manual trigger
      CI_VERSION: ${{ inputs.ci_version || github.event.inputs.ci_version }}
      QT_VERSION: 6.11.1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Cache submodules
        uses: actions/cache@v4
        with:
          path: |
            .git/modules
            moonlight-common-c/moonlight-common-c
            qmdnsengine/qmdnsengine
            app/SDL_GameControllerDB
            h264bitstream/h264bitstream
            libs
            imgui/imgui
            imgui/implot
          key: submodules-${{ runner.os }}-${{ hashFiles('.gitmodules') }}-${{ github.sha }}
          restore-keys: |
            submodules-${{ runner.os }}-${{ hashFiles('.gitmodules') }}-

      - name: Initialize submodules
        run: git submodule update --init --recursive --depth 1

      - name: Install create-dmg (macOS)
        run: npm install --global create-dmg

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: macos-15-qt${{ env.QT_VERSION }}
          max-size: 500M

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{ env.QT_VERSION }}
          aqtsource: 'git+https://github.com/miurahr/aqtinstall.git@9edeb24ae65361fd032a063a0b0148764eff09c5'

      - name: Build Package
        shell: bash
        run: bash scripts/generate-dmg.sh Release

      - name: Upload Binaries (macOS)
        uses: actions/upload-artifact@v5
        with:
          name: Moonlight-macOS-${{ env.CI_VERSION }}
          path: build/installer-Release/*.dmg
          compression-level: 0
          if-no-files-found: error

      - name: Upload Symbols
        uses: actions/upload-artifact@v6
        with:
          name: zDevDbgSyms-macOS-${{ env.CI_VERSION }}
          path: build/installer-*/*.dsym/*
          if-no-files-found: error
